# Site settings
title: Kristin Reddington
header-img: img/home-bg.png
email: kristinreddington@gmail.com
copyright_name: kristinreddington
description: > # this means to ignore newlines until "baseurl:"
  An aspiring coder's diary 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kristinreddington
learn_profile: kristinreddington
email_username: kristinreddington@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
